export const GET_OAUTH_REQUEST = 'GET_OAUTH_REQUEST'
export const GET_OAUTH_SUCCESS = 'GET_OAUTH_SUCCESS'
export const GET_OAUTH_FAIL = 'GET_OAUTH_FAIL'
export const GET_OAUTH_LOGOUT = 'GET_OAUTH_LOGOUT'
